### ISSUE TITLE
Running cmk with -p causes "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by cdstudios** [apache/cloudstack-cloudmonkey#35]
If I just run cmk it works fine using the 'default' server profile
```
>>>>~ $ cmk list virtualmachines | wc -l
    8290
>>>>~ $ cmk
Apache CloudStack 🐵 CloudMonkey 6.0.0-beta2
Report issues: https://github.com/apache/cloudstack-cloudmonkey/issues

(controlled) 🐱 >
>>>>~ $ bat .cmk/config
       │ File: .cmk/config
   6   │ profile    = controlled
```

But if I specify any profile via -p, including the 'default' it throws:
```
>>>>~ $ cmk -p controlled
Apache CloudStack 🐵 CloudMonkey 6.0.0-beta2
Report issues: https://github.com/apache/cloudstack-cloudmonkey/issues

(controlled) 🐱 > list virtualmachines
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x126ee0b]

goroutine 1 [running]:
github.com/apache/cloudstack-cloudmonkey/cmd.NewAPIRequest(0xc000cf2030, 0xc000783340, 0x13, 0xc00072a620, 0x0, 0x0, 0x0, 0x1058500, 0xc0000b1670, 0x49)
	/home/bhaisaab/Lab/apache/cloudmonkey/cmd/network.go:185 +0x23b
github.com/apache/cloudstack-cloudmonkey/cmd.init.0.func1(0xc000cf2030, 0xc000cf2030, 0xc000b80f60)
	/home/bhaisaab/Lab/apache/cloudmonkey/cmd/api.go:79 +0x2af
github.com/apache/cloudstack-cloudmonkey/cli.ExecCmd(0xc00072a620, 0x2, 0x2, 0x2, 0x2)
	/home/bhaisaab/Lab/apache/cloudmonkey/cli/exec.go:67 +0x2d0
github.com/apache/cloudstack-cloudmonkey/cli.ExecLine(0xc000bb0f40, 0x14, 0xc000a55020, 0xc0000b1b28)
	/home/bhaisaab/Lab/apache/cloudmonkey/cli/exec.go:51 +0x166
github.com/apache/cloudstack-cloudmonkey/cli.ExecPrompt.func1(0xc000bb0f40, 0x14)
	/home/bhaisaab/Lab/apache/cloudmonkey/cli/prompt.go:41 +0x39
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000c99080)
	/home/bhaisaab/Lab/apache/cloudmonkey/vendor/github.com/c-bata/go-prompt/prompt.go:85 +0x75b
github.com/apache/cloudstack-cloudmonkey/cli.ExecPrompt()
	/home/bhaisaab/Lab/apache/cloudmonkey/cli/prompt.go:78 +0x49f
main.main()
	/home/bhaisaab/Lab/apache/cloudmonkey/cmk.go:79 +0x257
```

On MacOS 10.12.6

**Comment by rhtyd** [comment]
Thanks for reporting @cdstudios I'll get back to you soon. For now run cmk set profile, and then use cmk on command line.

**Comment by rhtyd** [comment]
@cdstudios can you try the latest master, I'll update the binaries shortly.
