### ISSUE TITLE
Index out of range exception when autocompleting on list vmsnapshots

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-cloudmonkey#41]
![index-out-of-range](https://user-images.githubusercontent.com/13551960/51023246-1fd3ed80-158f-11e9-9bf9-5346ecebf5ed.gif)

Steps: 
1. Type list vmsnapshots
2. tab and the autocompletion option will appear
3. enter the options 'window'
4. press arrow down to navigate down

Following exception appears: 
```
(localcloud) SBCM5> > list vmsnapshot panic: runtime error: index out of range

goroutine 1 [running]:
github.com/c-bata/go-prompt.(*CompletionManager).GetSelectedSuggestion(0xc000097d60, 0xc000c860c0, 0xc000097d60, 0x26, 0x0, 0x0)
	/home/shapeblue/Documents/cloudstack-cloudmonkey/vendor/github.com/c-bata/go-prompt/completion.go:50 +0x14c
github.com/c-bata/go-prompt.(*Render).Render(0xc000079790, 0xc000c860c0, 0xc000097d60)
	/home/shapeblue/Documents/cloudstack-cloudmonkey/vendor/github.com/c-bata/go-prompt/render.go:209 +0x360
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000c74800)
	/home/shapeblue/Documents/cloudstack-cloudmonkey/vendor/github.com/c-bata/go-prompt/prompt.go:92 +0x53f
github.com/apache/cloudstack-cloudmonkey/cli.ExecPrompt()
	/home/shapeblue/Documents/cloudstack-cloudmonkey/cli/prompt.go:70 +0x3c7
main.main()
	/home/shapeblue/Documents/cloudstack-cloudmonkey/cmk.go:79 +0x257
[root@trl-1781-v-M7-bstoyanov-mgmt1 ~]#
```

**Comment by borisstoyanov** [comment]
Cloud not reproduce in beta v3
